DELETE http://localhost:3001/api/eventi/visestruko/62b5b9ca298a5c46bf330284
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJhZGFrMDEiLCJlbWFpbCI6InJhZGFrMDFAZ21haWwuY29tIiwidWxvZ2EiOiJhZG1pbiIsImlkIjoiNjJiNWI5Y2EyOThhNWM0NmJmMzMwMjg0IiwiaWF0IjoxNjU2MTgzNjI3fQ.KPdhwSQCm-Vttv1QVnt1BVdB2QWIYIIYNZigkrK2yCo