GET http://localhost:3001/api/prijave
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Iml2YW4xMjMiLCJlbWFpbCI6Iml2YW5pdmljMUBnbWFpbC5jb20iLCJ1bG9nYSI6ImtvcmlzbmlrIiwiaWQiOiI2MmI0ZTA1NDQ2YWQxMTA2OTU2ODVhMzkiLCJpYXQiOjE2NTYxNzcwMzN9.G0HCkn3UMEWCAh-QwOfLvLtQisdONt4PloY139_nQek
