GET http://localhost:3001/api/korisnici
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJhZGFrMDEiLCJlbWFpbCI6InJhZGFrMDFAZ21haWwuY29tIiwidWxvZ2EiOiJhZG1pbiIsImlkIjoiNjJiNWI5Y2EyOThhNWM0NmJmMzMwMjg0IiwiaWF0IjoxNjU2MDc3Nzg2fQ.q0hBhKJ4mY4wKs0ACQiAgpB7SlOa2RtUFi-J5PIXB_U