PUT http://localhost:3001/api/eventi/62b60e70b11494404f1d312f
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Iml2YW4xMjMiLCJlbWFpbCI6Iml2YW5pdmljMUBnbWFpbC5jb20iLCJ1bG9nYSI6ImtvcmlzbmlrIiwiaWQiOiI2MmI0ZTA1NDQ2YWQxMTA2OTU2ODVhMzkiLCJpYXQiOjE2NTYwOTgyNjF9.ELro4P_Me6DQdqsUkMw6cOEkdHh-YMag5LPPAOt84YQ

{
    "cijena": 30
}